---
sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"  # debian 9 stretch
  - "3.6"  # fedora 27
  - "3.7"  # fedora 29
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install -r test_requirements.txt"
# command to run tests
script: nosetests
