---
sudo: false
dist: xenial
language: python
python:
  - "2.7"
  - "3.4"  # (oldest supported by both travis' xenial and lxml)
  - "3.5"  # debian 9 stretch
  - "3.6"  # fedora 27
  - "3.7"  # fedora 29

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
script:
  - nosetests
