#!/bin/bash
#
# Run a Nagios passive check and submit its result via the CGI interface
#

# Configuration
#
# HTTP_USER=fnord
# HTTP_PASS=2342
# HTTP_URL=https://nagios.bl0rg.net/cgi-bin/nagios3/cmd.cgi
. $0.conf

# Parameters
host="$1"
service="$2"
shift 2
check="$@"

# Run check
plugin_output=`$check 2>&1`
plugin_state=$?

echo "$plugin_output"

# URL-Encode output
plugin_output=`echo "$plugin_output" | sed 's#\}#\\\\}#'`
plugin_output=`perl -MURI::Escape -e "print uri_escape(q{$plugin_output})"`

# Submit
wget -O - --quiet \
  --http-user="$HTTP_USER" --http-password="$HTTP_PASS" \
  --post-data \
  "cmd_typ=30&cmd_mod=2&host=$host&service=$service&plugin_state=$plugin_state&plugin_output=$plugin_output&btnSubmit=Commit" \
  $HTTP_URL >/dev/null
if [ "$?" != "0" ]; then
  echo "ERROR submitting check result to Nagios" >&2
fi
